-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 97b88d9610bcc03982ddac33caba98bb2b751f5f
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: flake8
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: 50e0be95e292cac913cc3c6fd44b3d6b51d104c5
    hooks:
    -   id: reorder-python-imports
